version: "3.3"

services:
    app:
        build: 
            context: ../.
            dockerfile: Dockerfile
        environment:
            # any env vars you want to add
            - FOO=BAR
        ports:
            - "8000:8000"

        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]